version: '3'
services:
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
    volumes:
      - mi-mysql-vol:/var/lib/mysql
    networks:
      mi-mysql-red:
        ipv4_address: 172.24.0.12
    container_name: mi-mysql

  dashboard:
    image: phpmyadmin
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
    ports:
      - 8080:80
    links:
      - db
    networks:
      mi-mysql-red:
        ipv4_address: 172.25.0.11
    container_name: mi-dashboard

volumes:
  mi-mysql-vol:

networks:
  mi-mysql-red:
    ipam:
      config:
        - subnet: 172.25.0.0/16