version: '3'

services:
  mi-mongo:
    container_name: mi-mongo
    image: mongo
    volumes:
      - mongo-vol:/data/db
    networks:
      mongo-node-net:
        ipv4_address: 172.40.0.10
    restart: always

  mi-node:
    container_name: mi-node
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080
    networks:
      mongo-node-net:
        ipv4_address: 172.40.0.11
      node-nginx-net:
        ipv4_address: 172.80.0.10
    restart: always

  mi-nginx:
    container_name: mi-nginx
    image: nginx
    ports:
      - 80:80
    networks:
      node-nginx-net:
        ipv4_address: 172.80.0.11
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - mi-node
    restart: always

volumes:
  mongo-vol:

networks:
  mongo-node-net:
    ipam:
      driver: default
      config:
        - subnet: 172.40.0.0/16
  node-nginx-net:
    ipam:
      driver: default
      config:
        - subnet: 172.80.0.0/16
